#!/bin/sh

set -ue

OUT_DIR=/tmp/tidb_binlog_pitr_test

# kill drainer, util no drainer process is running
while :
do
        drainer_num=`ps aux > temp && grep "drainer -log-file" temp | wc -l && rm temp`
        if [ $drainer_num -ne 0 ]; then
                killall drainer || true
                sleep 1
        else
                break
        fi
done

config=${TEST_DIR-.}/config/drainer.toml

echo $(pwd)
echo $config

echo "[$(date)] <<<<<< START IN TEST ${TEST_NAME-} FOR: $config >>>>>>" >> "$OUT_DIR/drainer.log"

if [ -f "$config" ]
then
	drainer -log-file $OUT_DIR/drainer.log -config $config $* >> $OUT_DIR/drainer.log 2>&1
else
	drainer -log-file $OUT_DIR/drainer.log -data-dir $OUT_DIR/drainer/ -dest-db-type file -pd-urls http://127.0.0.1:2379 $* >> $OUT_DIR/drainer.log 2>&1
fi
